
// Generated by Page Builder
import Page from './Page';
import _    from 'lodash';

export default {

    $pages() {
        return Object.values(this).filter(page => page instanceof Page);
    },

    $blogs() {
        return this.$pages().filter(page => page.blog).sort(Page.compareDates);
    },

    $search(searchText) {
        const regex   = new RegExp(_.escapeRegExp(_.escape(searchText)), 'i');
        const results = [];
        for (const page of this.$pages()) {
            if (page.$searchRegex(regex)) {
                results.push(page);
            }
        }
        return results;
    },

    'about': new Page({
        name: 'about',
        content: 'This is the about page!',
        plainTxt: 'This is the about page!\n',
        route: '/about',
        layout: '../layouts/API',
        title: 'chip-gr8 | About',
        place: 'about',
    }),
    'index': new Page({
        name: 'index',
        content: '# Introduction\n\nProject page dedicated to the demonstration and information of fourth year design project.\n\nWe are currently in project planning phase so stay tuned for future updates!\n\n# About\n\nThe project pertains to the design and implementation of a Chip-8 emulator and AI research environment. We hope to design a high performance emulation engine with a Python API for integration with modern Machine Learning and AI libraries. Future work would be to add more architectures to the emulator.\n\n# Timeline\n\nProject set to be completed by August 9th, 2019.\n',
        plainTxt: 'Introduction\nProject page dedicated to the demonstration and information of fourth year design project.\nWe are currently in project planning phase so stay tuned for future updates!\nAbout\nThe project pertains to the design and implementation of a Chip-8 emulator and AI research environment. We hope to design a high performance emulation engine with a Python API for integration with modern Machine Learning and AI libraries. Future work would be to add more architectures to the emulator.\nTimeline\nProject set to be completed by August 9th, 2019.\n',
        route: '/index',
        layout: '../layouts/API',
        title: 'chip-gr8',
        subtitle: 'Chip 8 emulation for AI',
        place: 'home',
    }),
    'reference': new Page({
        name: 'reference',
        content: 'This is the reference page!',
        plainTxt: 'This is the reference page!\n',
        route: '/reference',
        layout: '../layouts/API',
        title: 'chip-gr8 | Reference',
        place: 'reference',
    }),

};
