
// Generated by Page Builder
import Page from './Page';
import _    from 'lodash';

export default {

    $pages() {
        return Object.values(this).filter(page => page instanceof Page);
    },

    $blogs() {
        return this.$pages().filter(page => page.blog).sort(Page.compareDates);
    },

    $search(searchText) {
        const regex   = new RegExp(_.escapeRegExp(_.escape(searchText)), 'i');
        const results = [];
        for (const page of this.$pages()) {
            if (page.$searchRegex(regex)) {
                results.push(page);
            }
        }
        return results;
    },

    'about': new Page({
        name: 'about',
        content: "# Meet Our Team\n\nWe are a group of Software, and Electrical, Engineering students from the University of Victoria. With passions for programming, artificial intelligence, and gaming, we came together to deliver an artificial intelligence tool that will enable future generations to share in our love for technology and creating something new.\n\n![placeholder](../static/img/Eric.png)\n![placeholder](../static/img/Torrey.png)\n![placeholder](../static/img/Jon.png)\n![placeholder](../static/img/James.png)\n![placeholder](../static/img/Andrew2.png)\n![placeholder](../static/img/Forrest.png)\n\n# Acknowledgements\nSeveral people made this project possible and we would like to acknowledge their involvement in Chip-Gr8's development journey, and extend to them our deepest thanks.\n\n## Faculty Supervisor\n\n#### Rich Little\n![placeholder](../static/img/placeholder.png)\n\nWe chose Rich Little as our faculty supervisor for his background in algorithms and based on our positive experiences with him in CSC 225 and 226 courses. He was responsible for supervising the project during its development cycle and for marking all of the milestones. Thank you to Rich Little for the help he provided along the way.\n\n\n## Supporters\n\n#### Dr. Xiaodai Dong\nThank you to Dr. Xiaodai Dong for being the primary instructor this semester.\n\n#### Dr. T. Ilamparithi\nThank you to Dr. Ilamparithi for being the course coordinator this semester.\n\n#### Sai Prakash Reddy Konda\nThank you to the TA for their help with the course.",
        plainTxt: 'Meet Our Team\nWe are a group of Software, and Electrical, Engineering students from the University of Victoria. With passions for programming, artificial intelligence, and gaming, we came together to deliver an artificial intelligence tool that will enable future generations to share in our love for technology and creating something new.\nplaceholder\nplaceholder\nplaceholder\nplaceholder\nplaceholder\nplaceholder\nAcknowledgements\nSeveral people made this project possible and we would like to acknowledge their involvement in Chip-Gr8&#39;s development journey, and extend to them our deepest thanks.\nFaculty Supervisor\nRich Little\nplaceholder\nWe chose Rich Little as our faculty supervisor for his background in algorithms and based on our positive experiences with him in CSC 225 and 226 courses. He was responsible for supervising the project during its development cycle and for marking all of the milestones. Thank you to Rich Little for the help he provided along the way.\nSupporters\nDr. Xiaodai Dong\nThank you to Dr. Xiaodai Dong for being the primary instructor this semester.\nDr. T. Ilamparithi\nThank you to Dr. Ilamparithi for being the course coordinator this semester.\nSai Prakash Reddy Konda\nThank you to the TA for their help with the course.\n',
        route: '/about',
        layout: '../layouts/API',
        title: 'chip-gr8 | About',
        place: 'about',
    }),
    'index': new Page({
        name: 'index',
        content: 'Welcome to Chip-Gr8! This project was the capstone project of six Engineering students at the University of Victoria. \nBy combining our passions for gaming and artificial intelligence, we created a CHIP-8 emulator that doubles as a tool for learning how to develop Python AI programs. The aim of this project was to give new generations of programmers a stepping stone application into the world of AI.\n',
        plainTxt: 'Welcome to Chip-Gr8! This project was the capstone project of six Engineering students at the University of Victoria. \nBy combining our passions for gaming and artificial intelligence, we created a CHIP-8 emulator that doubles as a tool for learning how to develop Python AI programs. The aim of this project was to give new generations of programmers a stepping stone application into the world of AI.\n',
        route: '/index',
        layout: '../layouts/Docs',
        title: 'chip-gr8',
        subtitle: 'Chip 8 Emulation for AI',
        place: 'home',
    }),
    'project': new Page({
        name: 'project',
        content: '# The Project\n\nThe project pertains to the design and implementation of a Chip-8 emulator and AI research environment. We hope to design a high performance emulation engine with a Python API for integration with modern Machine Learning and AI libraries. Future work would be to add more architectures to the emulator.',
        plainTxt: 'The Project\nThe project pertains to the design and implementation of a Chip-8 emulator and AI research environment. We hope to design a high performance emulation engine with a Python API for integration with modern Machine Learning and AI libraries. Future work would be to add more architectures to the emulator.\n',
        route: '/project',
        layout: '../layouts/Project',
        title: 'chip-gr8 | Project',
        place: 'project',
        timeline: [
            {
                title: 'Early May',
                content: 'Started brainstorming ideas for the course project.',
            },
            {
                title: 'Mid May',
                content: 'Idea to develop a CHIP-8 emulator with AI teaching capabilities solidified; documentation is started. Project is named "CHIP-GR8" (pronounced Chip-Great).',
            },
            {
                title: 'Late May',
                content: 'Design documentation is filled out via team discussions Prototyping work begins.',
            },
            {
                title: 'Early June',
                content: 'Python wrapper and C-based emulator programming begins. Work is focused on the C-based emulator and the CTypes integration.',
            },
            {
                title: 'Mid June',
                content: 'Visualization is completed; CHIP-8 ROMs can be visualized with no input. mulator bugs are fixed en masse to ensure it runs in Windows, Mac, and Linux.',
            },
            {
                title: 'Late June',
                content: 'C-based emulator is completed, therefore project milestone 1 is completed. Python integration is completed, therefore project milestone 2 is completed. Support for keyboard input is operational, therefore project milestone 3 is completed ahead of schedule. Memory visualization milestone is started. Final bugs are squashed from previous milestones',
            },
            {
                title: 'Early July',
                content: 'Development on AI tools has begun; these will be used when developing. AIs Memory visualization is working minimally, progress still being made and bugs being fixed.',
            },
            {
                title: 'Mid July',
                content: 'Memory visualization module is completed, therefore concluding milestone 4. AI tools have been completed, therefore completing milestone 5. Development on example AIs begins',
            },
            {
                title: 'Late July',
                content: 'Example AIs are worked on to provide demonstration-worthy agents. Final bugs are wrapped up if time permits.',
            },
        ],
    }),

};
