
# !!! DO NOT MODIFY THIS FILE !!!!
#
# This file was autogenerated `defineVMStruct.py`.
# If you need to modify this struct modify the definition in that file.

import ctypes

class Chip8VMStruct(ctypes.Structure):
    _pack_   = 1
    _fields_ = [
        ('RAM', ctypes.c_uint8 * 0x1000), # Main memory
        ('VRAM', ctypes.c_uint8 * (64 * 32)), # Video memory
        ('stack', ctypes.c_uint16 * 16), # Address stack
        ('SP', ctypes.c_uint8), # Stack pointer
        ('PC', ctypes.c_uint16), # Program counter
        ('I', ctypes.c_uint16), # Address register
        ('V', ctypes.c_uint8 * 16), # General purpose registers
        ('DT', ctypes.c_uint8), # Delay timer
        ('ST', ctypes.c_uint8), # Sound timer
        ('keys', ctypes.c_uint16), # Key IO registers
        ('clock', ctypes.c_uint64), # Time since simulation began
        ('ROM', ctypes.c_void_p), # ROM file pointer
        ('seed', ctypes.c_uint8), # Seed for RNG
    ]
